DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS City1;
DROP TABLE IF EXISTS City2;
CREATE TABLE City(ID int, NAME varchar, PRIMARY KEY (ID));
CREATE TABLE City2(ID int, NAME varchar, PRIMARY KEY (ID));
CREATE TABLE City3(ID int, NAME varchar, PRIMARY KEY (ID));
